import type { Metadata } from "next";
import "./globals.css";
import Header from "../../components/global/Header";
import Footer from "../../components/global/Footer";
import { useState } from "react";
import Signin from "../../components/global/auth/SignComponent";

export const metadata: Metadata = {
  title: "TripNest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative min-h-screen flex flex-col">
          <header className="w-full fixed top-0 left-0 z-10">
            <Header />
          </header>

          <main className="flex-1">{children}</main>

          <footer className="w-full">
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}
