import type { Metadata } from "next";
import "./globals.css";
import Header from "../../components/global/Header";
import Footer from "../../components/global/Footer";
import { AuthProvider } from "../../context/authContext";

export const metadata: Metadata = {
  title: "TripNest",
  description: "Generated by create next app",
  icons: "/tripNestSiteIcon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <div className="relative min-h-screen flex flex-col">
            <header className="w-full fixed ">
              <Header />
            </header>

            <main className="flex-1">{children}</main>

            <footer className="w-full">
              <Footer />
            </footer>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
